version: '3'

services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jaimelespates
      MYSQL_DATABASE: hothothot
      MYSQL_USER: hothothot
      MYSQL_PASSWORD: kJI6zkVYcXmo6Ebt
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: jaimelespates
    ports:
      - "8080:80"

  php-apache:
    build:
      context: ./conf
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./:/site
      - ./conf/php.ini:/usr/local/etc/php/conf.d/site.ini

volumes:
  datavolume:
